<?php

define('ERR_REQUEST_CONNECT_FAILED','-1');
define('ERR_REQUEST_NULL_PACKAGE','-2');
define('ERR_REQUEST_NULL_SOCKET','-3');
define('ERR_REQUEST_SEND_FAILED','-4');
define('ERR_REQUEST_RECEIVE_BAD_MSG','-5');
define('ERR_REQUEST_RECEIVE_BAD_MSG_HEADR','-6');

define('ERR_HEADER_BAD_MSG_TYPE','-7');
define('ERR_HEADER_BAD_HEAD_LENGTH','-8');
define('ERR_HEADER_BAD_CHECK_SUM','-9');
define('ERR_HEADER_UNPACK_FAILED','-10');

define('ERR_PACKAGE_UNPACK_BAD_PARAM_TYPE','-11');
define('ERR_PACKAGE_UNPACK_FAILED_A','-12');
define('ERR_PACKAGE_UNPACK_FAILED_B','-13');
define('ERR_PACKAGE_UNPACK_FAILED_C','-14');
define('ERR_PACKAGE_PACK_BAD_PARAM_TYPE','-15');

?>
